apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.networkAttachmentName }}
  namespace: {{ .Values.namespace }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-netshoot",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "{{ .Values.staticIP }}",
            "gateway": "{{ .Values.gateway }}"
          }
        ]
      }
    }
