apiVersion: v1
kind: Namespace
metadata:
  name: admin-kubernetes
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: netshoot-static-net
  namespace: admin-kubernetes
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br-netshoot",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.128.2.50/23",
          "gateway": "10.128.2.1"
        }
      ]
    }
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-static-deployment
  namespace: admin-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot-static
  template:
    metadata:
      labels:
        app: netshoot-static
      annotations:
        k8s.v1.cni.cncf.io/networks: netshoot-static-net
#      annotations:
#        k8s.v1.cni.cncf.io/networks: '[ { "name": "netshoot-static-net", "interfaceRequest": "eth0" } ]'
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: netshoot
#          image: ubuntu:22.04
          image: nicolaka/netshoot
          command: ["/bin/bash", "-c", "sleep infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
