#htpasswd -c -B -b users.htpasswd <username> <password>
#oc create secret generic htpasswd-secret --from-file=htpasswd=<path_to_users.htpasswd> -n openshift-config

---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
# stringData:
#   htpasswd: |
#     admin:$2y$05$X9QXbPq7CThJ44RkqP5UQuIB2N6okhzbt1iQe.9jI3LG8z2UjC6FS
#     user:$2y$05$SXT3oSB1nHEKQBPm8CArFOqvVKhj5s4oSodv6yX3kO0AzQMiRGp0q
data:
  htpasswd: YWRtaW46JDJ5JDA1JDBCNWYuMkQxa3BydGVNZmlIclR0ZE84Sm1MalVDWU55cGJ6ZDI0bjFaN2JoblJ1cTBYRkJpCnVzZXI6JDJ5JDA1JHouc2d1alF4d1RCNlh0bW9VS2ovUk9DWW04WW9oUHRvSS81VVc1c2xIU0NwaWRsTm1xZ0QyCg==
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret
