apiVersion: v1
baseDomain: local.zz
metadata:
  name: sno
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.4.0/24
platform:
  none: {}
  # baremetal:
  #   apiVIPs:
  #   - 192.168.4.99
  #   ingressVIPs:
  #   - 192.168.4.100 
pullSecret: '' 
additionalTrustBundle: |
    -----BEGIN CERTIFICATE-----
 
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
 
    -----END CERTIFICATE-----
