# ClusterRole: Erlaube das Erstellen eigener Namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-can-create-namespaces
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list"]

---
# ClusterRoleBinding: Weist dem Benutzer diese Rechte global zu
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user-create-ns
subjects:
  - kind: User
    name: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: user-can-create-namespaces
  apiGroup: rbac.authorization.k8s.io
